### ISSUE TITLE
Tests are failing when clean start

### ISSUE THREAD

**Issue by matthiaseigner** [rimiti/redis-keyman#29]
When checking out the project and running 
```bash
docker-compose up
```

following error occures
```
aclify    | > @aclify/aclify@1.5.0 test /opt/app
aclify    | > jest --coverage
aclify    |
aclify    |   console.warn node_modules/bluebird/js/release/debuggability.js:868
aclify    |     Unhandled rejection SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MySQL client
aclify    |         at Utils.Promise.tap.then.catch.err (/opt/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
aclify    |         at tryCatcher (/opt/app/node_modules/bluebird/js/release/util.js:16:23)
aclify    |         at Promise._settlePromiseFromHandler (/opt/app/node_modules/bluebird/js/release/promise.js:512:31)
aclify    |         at Promise._settlePromise (/opt/app/node_modules/bluebird/js/release/promise.js:569:18)
aclify    |         at Promise._settlePromise0 (/opt/app/node_modules/bluebird/js/release/promise.js:614:10)
aclify    |         at Promise._settlePromises (/opt/app/node_modules/bluebird/js/release/promise.js:689:18)
aclify    |         at Async.Object.<anonymous>.Async._drainQueue (/opt/app/node_modules/bluebird/js/release/async.js:133:16)
aclify    |         at Async.Object.<anonymous>.Async._drainQueues (/opt/app/node_modules/bluebird/js/release/async.js:143:10)
aclify    |         at Immediate.Async.drainQueues (/opt/app/node_modules/bluebird/js/release/async.js:17:14)
aclify    |         at runCallback (timers.js:672:20)
aclify    |         at tryOnImmediate (timers.js:645:5)
aclify    |         at processImmediate [as _immediateCallback] (timers.js:617:5)
```

this is because the versions are not fixed in the docker-compose and sequalize seems to not be capable to connect to mysql:8 for now

i will send a pull request to fix this issue in a minute

**Comment by rimiti** [comment]
It will be merged into the next release (v1.6.0).
Thank you @matthiaseigner !
